platform :ios, '7.0' 
pod 'YYWebImage'
pod 'YYText'
pod 'MJRefresh'
pod 'MJExtension'
pod 'FDFullscreenPopGesture', '1.1'
pod 'PureLayout'
pod 'WebViewJavascriptBridge', '~> 5.0'
pod 'ShareSDK3'
pod 'MOBFoundation'
pod 'ShareSDK3/ShareSDKUI'
pod 'ShareSDK3/ShareSDKPlatforms/QQ'
pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
pod "Qiniu", "~> 7.0"
pod 'Pingpp'
pod 'AVOSCloudIM'
pod 'JPush'